"""Add matricul column to Boiler model

Revision ID: 032494fc5e81
Revises: 
Create Date: 2024-09-01 01:25:26.055874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032494fc5e81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boiler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matricul', sa.String(length=100), nullable=True))
        batch_op.alter_column('client_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('responsible_person',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boiler', schema=None) as batch_op:
        batch_op.alter_column('responsible_person',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('client_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.drop_column('matricul')

    # ### end Alembic commands ###
